description: Sydney is a Postdoctoral Scholar at The Ohio State University developing frameworks for integrated species delimitation using high-resolution data and sound data practices.

plugins:
  - jekyll-seo-tag